### ISSUE TITLE
Azure NotificaitonHub Register Crash in iOS 13.0 and Above

### ISSUE THREAD

**Issue by ooikengsiang** [xamarin/XamarinComponents#676]
Azure Notification Hub calling register on iOS 13.0 and above will crash immediately. There has been a fix: https://github.com/Azure/azure-notificationhubs-ios/issues/30 but no C# binding library available yet.

**Comment by Laumania** [comment]
Listening in here as I have the exact same issue in my app. Crash as soon as I call "Register" on the hub. no exception to catch just a native crash it seems.

**Comment by ooikengsiang** [comment]
The currently workaround I have is to disable notification for iOS 13 and above which is not ideal at all :(

**Comment by Laumania** [comment]
Yeah it’s super annoying! Really hope someone can fix the package soon! :S

**Comment by Laumania** [comment]
@ooikengsiang By the way, now that I look into it, why is this issue created in this repo?
I don't see this repo being related to Azure Notification Hub? At least I'm using this package:
https://www.nuget.org/packages/Xamarin.Azure.NotificationHubs.iOS/1.2.5.2

UPDATE: Which I just discovered actually points back to this exact Github Repo :D
https://github.com/xamarin/XamarinComponents/tree/master/XPlat/AzureMessaging

**Comment by Laumania** [comment]
@ooikengsiang
Now we just need somebody how can translate this swift/objective/what-ever code into C# and update the Xamarin Azure Notification Hub iOS package.

It's all right there it seems:
https://github.com/Azure/azure-notificationhubs-ios/pull/31/commits/4b422ba3215330124327490e4de1d0f8200ba677#diff-675498bb0c47314c4e394a2e8b4da2cc

**Comment by OCP-team** [comment]
I really really want this to be fixed as well!

**Comment by Laumania** [comment]
@OCP-team Yeah, wonder why there ain't many many more people in here... guess all have this issue, they might just haven't discovered it yet.

I tagged @jamesmontemagno in a Xamarin forum thread too, he have helped before pointing the right people in here.

**Comment by AntRemo** [comment]
@Laumania I found this, but it is a different approach I believe.

https://stackoverflow.com/a/58028222/3260560

**Comment by sillerjp** [comment]
Hi @Laumania 

Also just discovered this, no push notifications, failure in Unregister methods. Waiting for fix or workaround.

**Comment by SevenMike** [comment]
Hi,

I have the same problem.
I tried the solution proposed at this link https://stackoverflow.com/a/58028222/3260560, 
but it is not possible to set the "description" property of the deviceToken object.

Suggestions or solutions?

**Comment by sillerjp** [comment]
@SevenMike The workaround would be to manually bind the iOS library that contains the fix and add it to your project or wait for the publisher to update the library.

**Comment by SevenMike** [comment]
@JPSiller I tried to manipulate the deviceToken parameter coming from the "RegisteredForRemoteNotifications" method : 

_byte[] dataBytes = new byte[deviceToken.Length];
System.Runtime.InteropServices.Marshal.Copy(deviceToken.Bytes, dataBytes, 0, Convert.ToInt32(deviceToken.Length));
String hexString = BitConverter.ToString(dataBytes).Replace("-", "");
deviceToken = NSData.FromString(hexString);_

But this doesn't work :(

**Comment by sillerjp** [comment]
Hi @SevenMike yes I did the same hoping that workaround would work but it didn't work, at least for me. We'll have to wait for an answer from the publisher of the binding library. If you really need this to be fixed asap you can try binding the library yourself and just adding the resulting DLL to your project.

**Comment by sillerjp** [comment]
It seems it is a matter of updating the framework file, I manually created the binding library and used the same ApiDefinition as the previous one. Compiled and now it is working but don't know how to contribute here to fix it in this repository.

If it helps someone here is the dll I created:
https://onedrive.live.com/?authkey=%21AOLYldSQf1oBfU0&cid=7A738AC2CBAF0040&id=7A738AC2CBAF0040%2121013&parId=root&action=locate

**Comment by SevenMike** [comment]
@JPSiller Thanks, it seems to work !! Waiting for a library update, I use this dll.

But I didn't understand the procedure you did to solve the problem. You could explain it please?

**Comment by sillerjp** [comment]
@SevenMike Sure, basically the native iOS framework for Azure Notification Hubs stopped working in iOS 13. Since the Xamarin Binding library used this version of the native framework, it stopped working too. 

Developers for the native iOS framework fixed this issue and released a new version, the Xamarin binding library has to be updated to use this new version. I just created the binding library with the new version of the framework. Here is a resource on how to create binding libraries:
https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/

I'm looking into doing this update directly in this repository so a nuget package can be created and everyone can get the fix.

**Comment by Laumania** [comment]
@JPSiller It would be awesome if you could do a Pull Request to this Xamarin nuget, and then we can hopefully have somebody with the right permissions push a nuget update too.

More and more people will discover they have this issue and end up here in this thread - lets get it fixed ASAP :)

Great work so far!

**Comment by sillerjp** [comment]
FYI Another developer did a pull request already for this issue so I assume we will get the nuget package relatively soon.

**Comment by Laumania** [comment]
@JPSiller That's awesome, guess we are a lot waiting for the nuget update :)

Is it this one you are referring to?
#686

**Comment by sillerjp** [comment]
@Laumania Yes that's the one, I think it all looks good so hopefully it is merged soon.

**Comment by Redth** [comment]
Updates were published to NuGet earlier today, please go give them a look!  This all should be fixed now.

**Comment by sillerjp** [comment]
Working fine for me, only change I had to do was removing the "async" part of the method name for some of the register methods. Thanks @Redth

**Comment by Redth** [comment]
Yep, we _fixed_ the poorly named methods in the previous version.  Thanks for the feedback!

**Comment by Laumania** [comment]
@JPSiller Are you on XCode 11 and therefore the Preview channel of VS on Mac?
On Stable VS for Mac and XCode 11 my app still crash on startup - before even getting to the notification stuff. I'm trying out Preview channel for VS in a moment, just wanted to here what you guys are on - just to be sure :)

**Comment by sillerjp** [comment]
@Laumania AFAIK There is no need to try preview channel in VSForMac I'm using latest stable version which should be compatible with Xcode 11. 

I'm running my build in a device with iOS 13. Might be a different issue or a linkage error. Try running your app without the linker enabled.

**Comment by Laumania** [comment]
@JPSiller Ok, it must be something else then, exactly why I asked. On a side note...on my Mac Stable and Preview is the same...or at least it doesn't find any updates when I switch right now.

Anyway...I'll try some other stuff because this is not related to the Notification Hub iOS update.

Thanks guys and especially @Redth for fixing it 💪

**Comment by jmlumpkin** [comment]
Thank you for fixing this. 

The documentation on docs.microsoft.com is not correct now due to this change. See https://docs.microsoft.com/en-us/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started. (issue being tracked at https://github.com/MicrosoftDocs/azure-docs/issues/40317). 

Did this switch from being async before and not now? I see both as being an option. But our function was not wrapped in an async, so we had to remove those postfixes to even compile (plan to revisit this). 

Since the documentation currently is not correct (I think you would get a compile error that the entire method is not async) what is the expected route here?
